# Generated by Django 3.0.3 on 2020-02-27 02:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tesks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, verbose_name='Titulo')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('markup', models.BooleanField(default=False, verbose_name='Terminado')),
                ('members', models.ManyToManyField(related_name='Membros', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Criador', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
