# Generated by Django 3.0.3 on 2020-02-27 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200227_1450'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
