# Generated by Django 3.0.3 on 2020-02-27 15:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_delete_perfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='user',
        ),
        migrations.AddField(
            model_name='tasks',
            name='user',
            field=models.ManyToManyField(related_name='Criador', to=settings.AUTH_USER_MODEL),
        ),
    ]
