# Generated by Django 3.0.3 on 2020-02-27 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200227_1519'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='members',
        ),
    ]
