# Generated by Django 3.0.3 on 2020-02-28 01:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_tasks_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='begin',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data_Cadastro'),
        ),
        migrations.AddField(
            model_name='tasks',
            name='end',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data_Cadastro'),
        ),
    ]
