# Generated by Django 3.0.3 on 2020-02-28 15:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200228_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='begin',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Início'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='end',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Fim'),
        ),
    ]
