# Generated by Django 3.0.3 on 2020-03-01 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20200228_1546'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=60)),
                ('task', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Tarefa', to='core.Tasks')),
            ],
        ),
    ]
