# Generated by Django 3.0.3 on 2020-03-01 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200301_2042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintasks',
            name='task',
        ),
        migrations.AddField(
            model_name='maintasks',
            name='task',
            field=models.ManyToManyField(blank=True, default=1, related_name='Tarefa', to='core.Tasks'),
        ),
    ]
