# Generated by Django 3.0.3 on 2020-03-02 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200301_2044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintasks',
            name='task',
        ),
        migrations.AddField(
            model_name='tasks',
            name='main_task',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='core.MainTasks'),
        ),
    ]
